commerce_printful.settings:
  type: config_object
  mapping:
    api_base_url:
      type: string
      label: 'API base URL'
    api_key:
      type: string
      label: 'API key'
    variation_bundles:
      type: sequence
      label: 'Product variation bundles that will be synchronized with Printful'
      sequence:
        type: string
