commerce_printful.settings:
  type: config_object
  mapping:
    api_base_url:
      type: string
      label: 'API base URL'
    api_key:
      type: string
      label: 'API key'
    variation_sync_data:
      type: sequence
      label: 'Product variation bundles that will be synchronized with Printful'
      sequence:
        type: mapping
        mapping:
          attribute_mapping:
            type: mapping
            mapping:
              color:
                type: string
              size:
                type: string
          commerce_store_id:
            type: string
          api_key:
            type: string