commerce_printful.settings:
  type: config_object
  mapping:
    api_base_url:
      type: string
      label: 'Printful API base URL'

commerce_printful.printful_store.*:
  type: config_entity
  label: 'Printful store configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    apiKey:
      type: string
      label: 'Printful API key'
    commerceStoreId:
      type: string
      label: 'Commerce store ID'
    productBundle:
      type: string
      label: 'Commerce Product type to sync with this store'
    attributeMapping:
      type: mapping
      label: 'Printful attributes mapping'
      mapping:
        color:
          type: string
        size:
          type: string
        image:
          type: string
    syncOrders:
      type: boolean
      label: 'Should paid orders be sent to Printful?'
    draftOrders:
      type: boolean
      label: 'Should orders be exported as drafts?'
    webhooks:
      type: sequence
      label: 'Enabled webhooks'
